version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - echo "Empezamos la instalacion dotnet"
  pre_build:
    commands:
      - echo "Empezamos la fase de compilacion"
      - dotnet restore MvcCoreAWSCodePipeLine/MvcCoreAWSCodePipeLine.csproj
  build:
    commands:
      - echo "Vamos a realizar una prueba"
      - dotnet build MvcCoreAWSCodePipeLine/MvcCoreAWSCodePipeLine.csproj
  post_build:
    commands:
      - echo "Empezamos publicacion"
      - dotnet publish -c release -o ./build_output MvcCoreAWSCodePipeLine/MvcCoreAWSCodePipeLine.csproj

artifacts:
  files:
    - ./build_output/**/*
